services:
  - type: web
    name: vision-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn training_backend.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
